DmxValue[] start
DmxValue[] end
uint32 delayMs
uint32 durationMs
uint8 curve

#Easing curve types
uint8 Linear = 0
uint8 InQuad = 1
uint8 OutQuad = 2
uint8 InOutQuad = 3
uint8 OutInQuad = 4
uint8 InCubic = 5
uint8 OutCubic = 6
uint8 InOutCubic = 7
uint8 OutInCubic = 8
uint8 InQuart = 9
uint8 OutQuart = 10
uint8 InOutQuart = 11
uint8 OutInQuart = 12
uint8 InQuint = 13
uint8 OutQuint = 14
uint8 InOutQuint = 15
uint8 OutInQuint = 16
uint8 InSine = 17
uint8 OutSine = 18
uint8 InOutSine = 19
uint8 OutInSine = 20
uint8 InExpo = 21
uint8 OutExpo = 22
uint8 InOutExpo = 23
uint8 OutInExpo = 24
uint8 InCirc = 25
uint8 OutCirc = 26
uint8 InOutCirc = 27
uint8 OutInCirc = 28
uint8 InElastic = 29
uint8 OutElastic = 30
uint8 InOutElastic = 31
uint8 OutInElastic = 32
uint8 InBack = 33
uint8 OutBack = 34
uint8 InOutBack = 35
uint8 OutInBack = 36
uint8 InBounce = 37
uint8 OutBounce = 38
uint8 InOutBounce = 39
uint8 OutInBounce = 40
uint8 Custom = 45

